package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class AccountInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.nickname
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.sex
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.portrait
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.state
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.id
     *
     * @return the value of account_info.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.id
     *
     * @param id the value for account_info.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.gmt_create
     *
     * @return the value of account_info.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.gmt_create
     *
     * @param gmtCreate the value for account_info.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.gmt_modified
     *
     * @return the value of account_info.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.gmt_modified
     *
     * @param gmtModified the value for account_info.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.is_deleted
     *
     * @return the value of account_info.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.is_deleted
     *
     * @param isDeleted the value for account_info.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_id
     *
     * @return the value of account_info.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_id
     *
     * @param accountId the value for account_info.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.nickname
     *
     * @return the value of account_info.nickname
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.nickname
     *
     * @param nickname the value for account_info.nickname
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.sex
     *
     * @return the value of account_info.sex
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.sex
     *
     * @param sex the value for account_info.sex
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.portrait
     *
     * @return the value of account_info.portrait
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.portrait
     *
     * @param portrait the value for account_info.portrait
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait == null ? null : portrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.state
     *
     * @return the value of account_info.state
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.state
     *
     * @param state the value for account_info.state
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }
}