package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class AccountToken implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_token.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_token.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_token.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_token.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_token.token
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_token.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_token.id
     *
     * @return the value of account_token.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_token.id
     *
     * @param id the value for account_token.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_token.gmt_create
     *
     * @return the value of account_token.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_token.gmt_create
     *
     * @param gmtCreate the value for account_token.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_token.gmt_modified
     *
     * @return the value of account_token.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_token.gmt_modified
     *
     * @param gmtModified the value for account_token.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_token.is_deleted
     *
     * @return the value of account_token.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_token.is_deleted
     *
     * @param isDeleted the value for account_token.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_token.token
     *
     * @return the value of account_token.token
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_token.token
     *
     * @param token the value for account_token.token
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_token.account_id
     *
     * @return the value of account_token.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_token.account_id
     *
     * @param accountId the value for account_token.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }
}