package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class Address implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.district
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.name
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.gmt_create
     *
     * @return the value of address.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.gmt_create
     *
     * @param gmtCreate the value for address.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.gmt_modified
     *
     * @return the value of address.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.gmt_modified
     *
     * @param gmtModified the value for address.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.is_deleted
     *
     * @return the value of address.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.is_deleted
     *
     * @param isDeleted the value for address.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.account_id
     *
     * @return the value of address.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.account_id
     *
     * @param accountId the value for address.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setAccountId(Boolean accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.district
     *
     * @return the value of address.district
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.district
     *
     * @param district the value for address.district
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detail
     *
     * @return the value of address.detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detail
     *
     * @param detail the value for address.detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.name
     *
     * @return the value of address.name
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.name
     *
     * @param name the value for address.name
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}