package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sku_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.first_category_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long firstCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.second_category_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long secondCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.title
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.introduce
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale_price
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.market_price
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.bonus_ratio
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Integer bonusRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.limit_per_order
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Integer limitPerOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.hidden
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean hidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.onsale
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean onsale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.free_delivery
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean freeDelivery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_create
     *
     * @return the value of goods.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_create
     *
     * @param gmtCreate the value for goods.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_modified
     *
     * @return the value of goods.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_modified
     *
     * @param gmtModified the value for goods.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_deleted
     *
     * @return the value of goods.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_deleted
     *
     * @param isDeleted the value for goods.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sku_id
     *
     * @return the value of goods.sku_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sku_id
     *
     * @param skuId the value for goods.sku_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.first_category_id
     *
     * @return the value of goods.first_category_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getFirstCategoryId() {
        return firstCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.first_category_id
     *
     * @param firstCategoryId the value for goods.first_category_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setFirstCategoryId(Long firstCategoryId) {
        this.firstCategoryId = firstCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.second_category_id
     *
     * @return the value of goods.second_category_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getSecondCategoryId() {
        return secondCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.second_category_id
     *
     * @param secondCategoryId the value for goods.second_category_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setSecondCategoryId(Long secondCategoryId) {
        this.secondCategoryId = secondCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.title
     *
     * @return the value of goods.title
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.title
     *
     * @param title the value for goods.title
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.introduce
     *
     * @return the value of goods.introduce
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.introduce
     *
     * @param introduce the value for goods.introduce
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale_price
     *
     * @return the value of goods.sale_price
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale_price
     *
     * @param salePrice the value for goods.sale_price
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.market_price
     *
     * @return the value of goods.market_price
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.market_price
     *
     * @param marketPrice the value for goods.market_price
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setMarketPrice(Long marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.bonus_ratio
     *
     * @return the value of goods.bonus_ratio
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Integer getBonusRatio() {
        return bonusRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.bonus_ratio
     *
     * @param bonusRatio the value for goods.bonus_ratio
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setBonusRatio(Integer bonusRatio) {
        this.bonusRatio = bonusRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.limit_per_order
     *
     * @return the value of goods.limit_per_order
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Integer getLimitPerOrder() {
        return limitPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.limit_per_order
     *
     * @param limitPerOrder the value for goods.limit_per_order
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setLimitPerOrder(Integer limitPerOrder) {
        this.limitPerOrder = limitPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.hidden
     *
     * @return the value of goods.hidden
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.hidden
     *
     * @param hidden the value for goods.hidden
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.onsale
     *
     * @return the value of goods.onsale
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getOnsale() {
        return onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.onsale
     *
     * @param onsale the value for goods.onsale
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setOnsale(Boolean onsale) {
        this.onsale = onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.free_delivery
     *
     * @return the value of goods.free_delivery
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getFreeDelivery() {
        return freeDelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.free_delivery
     *
     * @param freeDelivery the value for goods.free_delivery
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setFreeDelivery(Boolean freeDelivery) {
        this.freeDelivery = freeDelivery;
    }
}