package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class GoodsImage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image.goods_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image.image_url
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image.id
     *
     * @return the value of goods_image.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image.id
     *
     * @param id the value for goods_image.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image.gmt_create
     *
     * @return the value of goods_image.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image.gmt_create
     *
     * @param gmtCreate the value for goods_image.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image.gmt_modified
     *
     * @return the value of goods_image.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image.gmt_modified
     *
     * @param gmtModified the value for goods_image.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image.is_deleted
     *
     * @return the value of goods_image.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image.is_deleted
     *
     * @param isDeleted the value for goods_image.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image.goods_id
     *
     * @return the value of goods_image.goods_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image.goods_id
     *
     * @param goodsId the value for goods_image.goods_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image.image_url
     *
     * @return the value of goods_image.image_url
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image.image_url
     *
     * @param imageUrl the value for goods_image.image_url
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }
}