package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class OperationLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.account_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.type
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.old_data
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private String oldData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.new_data
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private String newData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operation_log
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.id
     *
     * @return the value of operation_log.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.id
     *
     * @param id the value for operation_log.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.gmt_create
     *
     * @return the value of operation_log.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.gmt_create
     *
     * @param gmtCreate the value for operation_log.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.gmt_modified
     *
     * @return the value of operation_log.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.gmt_modified
     *
     * @param gmtModified the value for operation_log.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.is_deleted
     *
     * @return the value of operation_log.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.is_deleted
     *
     * @param isDeleted the value for operation_log.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.account_id
     *
     * @return the value of operation_log.account_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.account_id
     *
     * @param accountId the value for operation_log.account_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.type
     *
     * @return the value of operation_log.type
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.type
     *
     * @param type the value for operation_log.type
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.old_data
     *
     * @return the value of operation_log.old_data
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public String getOldData() {
        return oldData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.old_data
     *
     * @param oldData the value for operation_log.old_data
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setOldData(String oldData) {
        this.oldData = oldData == null ? null : oldData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.new_data
     *
     * @return the value of operation_log.new_data
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public String getNewData() {
        return newData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.new_data
     *
     * @param newData the value for operation_log.new_data
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setNewData(String newData) {
        this.newData = newData == null ? null : newData.trim();
    }
}