package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.gmt_create
     *
     * @return the value of order.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.gmt_create
     *
     * @param gmtCreate the value for order.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.gmt_modified
     *
     * @return the value of order.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.gmt_modified
     *
     * @param gmtModified the value for order.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.is_deleted
     *
     * @return the value of order.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.is_deleted
     *
     * @param isDeleted the value for order.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}