package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class ShopInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.title
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.introduce
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.logo
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.invite_code
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.status
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.id
     *
     * @return the value of shop_info.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.id
     *
     * @param id the value for shop_info.id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.gmt_create
     *
     * @return the value of shop_info.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.gmt_create
     *
     * @param gmtCreate the value for shop_info.gmt_create
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.gmt_modified
     *
     * @return the value of shop_info.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.gmt_modified
     *
     * @param gmtModified the value for shop_info.gmt_modified
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.is_deleted
     *
     * @return the value of shop_info.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.is_deleted
     *
     * @param isDeleted the value for shop_info.is_deleted
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.account_id
     *
     * @return the value of shop_info.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.account_id
     *
     * @param accountId the value for shop_info.account_id
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.title
     *
     * @return the value of shop_info.title
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.title
     *
     * @param title the value for shop_info.title
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.introduce
     *
     * @return the value of shop_info.introduce
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.introduce
     *
     * @param introduce the value for shop_info.introduce
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.logo
     *
     * @return the value of shop_info.logo
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.logo
     *
     * @param logo the value for shop_info.logo
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.invite_code
     *
     * @return the value of shop_info.invite_code
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.invite_code
     *
     * @param inviteCode the value for shop_info.invite_code
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.status
     *
     * @return the value of shop_info.status
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.status
     *
     * @param status the value for shop_info.status
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}