package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class ShopIncomeDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_income_detail.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_income_detail.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_income_detail.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_income_detail.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_income_detail.account_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_income_detail.amount
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_income_detail.type
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_income_detail.id
     *
     * @return the value of shop_income_detail.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_income_detail.id
     *
     * @param id the value for shop_income_detail.id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_income_detail.gmt_create
     *
     * @return the value of shop_income_detail.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_income_detail.gmt_create
     *
     * @param gmtCreate the value for shop_income_detail.gmt_create
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_income_detail.gmt_modified
     *
     * @return the value of shop_income_detail.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_income_detail.gmt_modified
     *
     * @param gmtModified the value for shop_income_detail.gmt_modified
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_income_detail.is_deleted
     *
     * @return the value of shop_income_detail.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_income_detail.is_deleted
     *
     * @param isDeleted the value for shop_income_detail.is_deleted
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_income_detail.account_id
     *
     * @return the value of shop_income_detail.account_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_income_detail.account_id
     *
     * @param accountId the value for shop_income_detail.account_id
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_income_detail.amount
     *
     * @return the value of shop_income_detail.amount
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_income_detail.amount
     *
     * @param amount the value for shop_income_detail.amount
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_income_detail.type
     *
     * @return the value of shop_income_detail.type
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_income_detail.type
     *
     * @param type the value for shop_income_detail.type
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }
}