package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class WebsiteConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.id
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.gmt_create
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.gmt_modified
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.is_deleted
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.config_key
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    private String configKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.config_value
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_config
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.id
     *
     * @return the value of website_config.id
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.id
     *
     * @param id the value for website_config.id
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.gmt_create
     *
     * @return the value of website_config.gmt_create
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.gmt_create
     *
     * @param gmtCreate the value for website_config.gmt_create
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.gmt_modified
     *
     * @return the value of website_config.gmt_modified
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.gmt_modified
     *
     * @param gmtModified the value for website_config.gmt_modified
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.is_deleted
     *
     * @return the value of website_config.is_deleted
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.is_deleted
     *
     * @param isDeleted the value for website_config.is_deleted
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.config_key
     *
     * @return the value of website_config.config_key
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.config_key
     *
     * @param configKey the value for website_config.config_key
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.config_value
     *
     * @return the value of website_config.config_value
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.config_value
     *
     * @param configValue the value for website_config.config_value
     *
     * @mbg.generated Mon Sep 24 16:02:48 CST 2018
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }
}