package com.weafung.shop.model.po;

import java.io.Serializable;
import java.util.Date;

public class WebsiteConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.id
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.gmt_create
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.gmt_modified
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.is_deleted
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.key
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_config.value
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_config
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.id
     *
     * @return the value of website_config.id
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.id
     *
     * @param id the value for website_config.id
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.gmt_create
     *
     * @return the value of website_config.gmt_create
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.gmt_create
     *
     * @param gmtCreate the value for website_config.gmt_create
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.gmt_modified
     *
     * @return the value of website_config.gmt_modified
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.gmt_modified
     *
     * @param gmtModified the value for website_config.gmt_modified
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.is_deleted
     *
     * @return the value of website_config.is_deleted
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.is_deleted
     *
     * @param isDeleted the value for website_config.is_deleted
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.key
     *
     * @return the value of website_config.key
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.key
     *
     * @param key the value for website_config.key
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_config.value
     *
     * @return the value of website_config.value
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_config.value
     *
     * @param value the value for website_config.value
     *
     * @mbg.generated Sun Sep 23 23:53:26 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}