package com.weafung.shop.dao;

import com.weafung.shop.model.po.AccountToken;
import com.weafung.shop.model.po.AccountTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    long countByExample(AccountTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    int deleteByExample(AccountTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    int insert(AccountToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    int insertSelective(AccountToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    List<AccountToken> selectByExample(AccountTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") AccountToken record, @Param("example") AccountTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_token
     *
     * @mbg.generated Mon Sep 24 23:22:32 CST 2018
     */
    int updateByExample(@Param("record") AccountToken record, @Param("example") AccountTokenExample example);
}