package com.weafung.shop.dao;

import com.weafung.shop.model.po.GoodsImage;
import com.weafung.shop.model.po.GoodsImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    long countByExample(GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int deleteByExample(GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int insert(GoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int insertSelective(GoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    List<GoodsImage> selectByExample(GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") GoodsImage record, @Param("example") GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int updateByExample(@Param("record") GoodsImage record, @Param("example") GoodsImageExample example);
}