package com.weafung.shop.dao;

import com.weafung.shop.model.po.ShopInfo;
import com.weafung.shop.model.po.ShopInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    long countByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int deleteByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int insert(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int insertSelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    List<ShopInfo> selectByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int updateByExample(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);
}