package com.weafung.shop.dao;

import com.weafung.shop.model.po.ShopIncomeDetail;
import com.weafung.shop.model.po.ShopIncomeDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopIncomeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    long countByExample(ShopIncomeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int deleteByExample(ShopIncomeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int insert(ShopIncomeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int insertSelective(ShopIncomeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    List<ShopIncomeDetail> selectByExample(ShopIncomeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopIncomeDetail record, @Param("example") ShopIncomeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_income_detail
     *
     * @mbg.generated Mon Sep 24 22:15:09 CST 2018
     */
    int updateByExample(@Param("record") ShopIncomeDetail record, @Param("example") ShopIncomeDetailExample example);
}